### ISSUE TITLE
Got IOException while trying to open MediaExtractor.

### ISSUE THREAD

**Issue by chao9267** [jonataslaw/VideoCompress#113]
E/DefaultDataSource(12532): Got IOException while trying to open MediaExtractor.
E/DefaultDataSource(12532): java.io.IOException: Failed to instantiate extractor.
E/DefaultDataSource(12532): 	at android.media.MediaExtractor.nativeSetDataSource(Native Method)
E/DefaultDataSource(12532): 	at android.media.MediaExtractor.setDataSource(MediaExtractor.java:203)
E/DefaultDataSource(12532): 	at android.media.MediaExtractor.setDataSource(MediaExtractor.java:111)
E/DefaultDataSource(12532): 	at com.otaliastudios.transcoder.source.UriDataSource.applyExtractor(UriDataSource.java:28)
E/DefaultDataSource(12532): 	at com.otaliastudios.transcoder.source.DefaultDataSource.ensureExtractor(DefaultDataSource.java:49)
E/DefaultDataSource(12532): 	at com.otaliastudios.transcoder.source.DefaultDataSource.getTrackFormat(DefaultDataSource.java:178)
E/DefaultDataSource(12532): 	at com.otaliastudios.transcoder.TranscoderOptions$Builder.buildAudioDataSources(TranscoderOptions.java:340)
E/DefaultDataSource(12532): 	at com.otaliastudios.transcoder.TranscoderOptions$Builder.build(TranscoderOptions.java:401)
E/DefaultDataSource(12532): 	at com.otaliastudios.transcoder.TranscoderOptions$Builder.transcode(TranscoderOptions.java:417)
E/DefaultDataSource(12532): 	at com.example.video_compress.VideoCompressPlugin.onMethodCall(VideoCompressPlugin.kt:163)
E/DefaultDataSource(12532): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/DefaultDataSource(12532): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/DefaultDataSource(12532): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/DefaultDataSource(12532): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DefaultDataSource(12532): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/DefaultDataSource(12532): 	at android.os.Looper.loop(Looper.java:182)
E/DefaultDataSource(12532): 	at android.app.ActivityThread.main(ActivityThread.java:7782)
E/DefaultDataSource(12532): 	at java.lang.reflect.Method.invoke(Native Method)
E/DefaultDataSource(12532): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/DefaultDataSource(12532): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
E/MethodChannel#video_compress(12532): Failed to handle method call
E/MethodChannel#video_compress(12532): java.lang.RuntimeException: java.io.IOException: Failed to instantiate extractor.
E/MethodChannel#video_compress(12532): 	at com.otaliastudios.transcoder.source.DefaultDataSource.ensureExtractor(DefaultDataSource.java:52)
E/MethodChannel#video_compress(12532): 	at com.otaliastudios.transcoder.source.DefaultDataSource.getTrackFormat(DefaultDataSource.java:178)
E/MethodChannel#video_compress(12532): 	at com.otaliastudios.transcoder.TranscoderOptions$Builder.buildAudioDataSources(TranscoderOptions.java:340)
E/MethodChannel#video_compress(12532): 	at com.otaliastudios.transcoder.TranscoderOptions$Builder.build(TranscoderOptions.java:401)
E/MethodChannel#video_compress(12532): 	at com.otaliastudios.transcoder.TranscoderOptions$Builder.transcode(TranscoderOptions.java:417)
E/MethodChannel#video_compress(12532): 	at com.example.video_compress.VideoCompressPlugin.onMethodCall(VideoCompressPlugin.kt:163)
E/MethodChannel#video_compress(12532): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#video_compress(12532): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#video_compress(12532): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#video_compress(12532): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#video_compress(12532): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#video_compress(12532): 	at android.os.Looper.loop(Looper.java:182)
E/MethodChannel#video_compress(12532): 	at android.app.ActivityThread.main(ActivityThread.java:7782)
E/MethodChannel#video_compress(12532): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#video_compress(12532): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#video_compress(12532): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
E/MethodChannel#video_compress(12532): Caused by: java.io.IOException: Failed to instantiate extractor.
E/MethodChannel#video_compress(12532): 	at android.media.MediaExtractor.nativeSetDataSource(Native Method)
E/MethodChannel#video_compress(12532): 	at android.media.MediaExtractor.setDataSource(MediaExtractor.java:203)
E/MethodChannel#video_compress(12532): 	at android.media.MediaExtractor.setDataSource(MediaExtractor.java:111)
E/MethodChannel#video_compress(12532): 	at com.otaliastudios.transcoder.source.UriDataSource.applyExtractor(UriDataSource.java:28)
E/MethodChannel#video_compress(12532): 	at com.otaliastudios.transcoder.source.DefaultDataSource.ensureExtractor(DefaultDataSource.java:49)
E/MethodChannel#video_compress(12532): 	... 15 more
I/flutter (12532): Error from VideoCompress: 
I/flutter (12532):       Method: compressVideo
I/flutter (12532):       PlatformException(error, java.io.IOException: Failed to instantiate extractor., null, java.lang.RuntimeException: java.io.IOException: Failed to instantiate extractor.
I/flutter (12532): 	at com.otaliastudios.transcoder.source.DefaultDataSource.ensureExtractor(DefaultDataSource.java:52)
I/flutter (12532): 	at com.otaliastudios.transcoder.source.DefaultDataSource.getTrackFormat(DefaultDataSource.java:178)
I/flutter (12532): 	at com.otaliastudios.transcoder.TranscoderOptions$Builder.buildAudioDataSources(TranscoderOptions.java:340)
I/flutter (12532): 	at com.otaliastudios.transcoder.TranscoderOptions$Builder.build(TranscoderOptions.java:401)
I/flutter (12532): 	at com.otaliastudios.transcoder.TranscoderOptions$Builder.transcode(TranscoderOptions.java:417)
I/flutter (12532): 	at com.example.video_compress.VideoCompressPlugin.onMethodCall(VideoCompressPlugin.kt:163)
I/flutter (12532): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter (12532): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
I/flutter (12532): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
I/flutter (12532): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (12532): 	at android.os.MessageQueue.next(MessageQueue.java:336)
I/flutter (12532): 	at android.os.Looper.loop(Looper.java:182)
I/flutter (12532): 	at android.app.ActivityThread.main(ActivityThread.java:7782)
I/flutter (12532): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter (12532): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
I/flutter (12532): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
I/flutter (12532): Caused by: java.io.IOException: Failed to instantiate extractor.
I/flutter (12532): 	at android.media.MediaExtractor.nativeSetDataSource(Native Method)
I/flutter (12532): 	at android.media.MediaExtractor.setDataSource(MediaExtractor.java:203)
I/flutter (12532): 	at android.media.MediaExtractor.setDataSource(MediaExtractor.java:111)
I/flutter (12532): 	at com.otaliastudios.transcoder.source.UriDataSource.applyExtractor(UriDataSource.java:28)
I/flutter (12532): 	at com.otaliastudios.transcoder.source.DefaultDataSource.ensureExtractor(DefaultDataSource.java:49)
I/flutter (12532): 	... 15 more
I/flutter (12532): )
I/flutter (12532): *****null

**Comment by vitulgoyani** [comment]
same error i got

**Comment by zohreh-jamali** [comment]
I have the same issue

**Comment by HZRZCW** [comment]
same error i got

**Comment by ajay-drodify** [comment]
Same error any progress on this ?

**Comment by tking16** [comment]
It's 2023 and I'm getting this issue. Any help with this at all...?

**Comment by Oskarmos1** [comment]
2023 still got the same issue. Any progress?

**Comment by smallqs** [comment]
me too , 2024-07-11
initMediaExtractor: failed to create MediaExtractor
java.io.IOException: Failed to instantiate extractor.
	at android.media.MediaExtractor.nativeSetDataSource(Native Method)
	at android.media.MediaExtractor.setDataSource(MediaExtractor.java:203)
