### ISSUE TITLE
Bug: Unsupported value kotlin.Unit

### ISSUE THREAD

**Issue by vanfresh** [jonataslaw/VideoCompress#131]
```
E/MethodChannel#video_compress( 8597): Failed to handle method call
E/MethodChannel#video_compress( 8597): java.lang.IllegalArgumentException: Unsupported value: 'kotlin.Unit' of type 'class kotlin.Unit'
E/MethodChannel#video_compress( 8597): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:292)
E/MethodChannel#video_compress( 8597): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:59)
E/MethodChannel#video_compress( 8597): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/MethodChannel#video_compress( 8597): 	at com.example.video_compress.VideoCompressPlugin.onMethodCall(VideoCompressPlugin.kt:68)
E/MethodChannel#video_compress( 8597): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#video_compress( 8597): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#video_compress( 8597): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#video_compress( 8597): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#video_compress( 8597): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#video_compress( 8597): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#video_compress( 8597): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#video_compress( 8597): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#video_compress( 8597): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#video_compress( 8597): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by vanfresh** [comment]
The bug is coming from `deleteAllCache` method 
```
  "deleteAllCache" -> {
        result.success(Utility(channelName).deleteAllCache(context, result));
    }
```

**Comment by denes16** [comment]
same error here

**Comment by karthik-js** [comment]
any update on this issue?

**Comment by WatchDogsDev** [comment]
Same here. Anyone working on this package ?
