### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by JErazo7** [jonataslaw/VideoCompress#136]
I got this error when i choose a video from the gallery with [image_picker](https://pub.dev/packages/image_picker) and i passed it to compressVideo method  on a iphone X with iOS 15.0
```
#0      new MediaInfo.fromJson (package:video_compress/src/media/media_info.dart:43:21)
#1      Compress.compressVideo (package:video_compress/src/video_compress/video_compressor.dart:157:24)
<asynchronous suspension>
#2      DeviceRepository._compressVideo (package:belo/src/data/core/repositories/device_repository.dart:130:20)
<asynchronous suspension>
#3      DeviceRepository.getVideo (package:belo/src/data/core/repositories/device_repository.dart:90:30)
<asynchronous suspension>
#4      UserValidationController.getVideo (package:belo/src/logic/user/user_validation/user_validation_controller.dart:98:9)
<asynchronous suspension>
```

**Comment by AykutAcikgoz** [comment]
Same issue here after cropping video by using ffmpeg. If I call VideoCompress.cancelCompression() it does not throw an error but looks like not compressing video after this.
