### ISSUE TITLE
Null check operator used on a null value in Isolate

### ISSUE THREAD

**Issue by Tom3652** [jonataslaw/VideoCompress#143]
Hello and thanks for the package !

I try to compress the video in an isolate and i have the following error when making a Top-Level function : 

```
I/flutter (20324): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (20324): Exception: Null check operator used on a null value
I/flutter (20324): 
I/flutter (20324): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:121:86)
I/flutter (20324): #1      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:375:5)
I/flutter (20324): #2      CompressMixin.initProcessCallback (package:video_compress/src/progress_callback/compress_mixin.dart:11:14)
I/flutter (20324): #3      new _VideoCompressImpl._ (package:video_compress/src/video_compress/video_compressor.dart:15:5)
I/flutter (20324): #4      _VideoCompressImpl.instance (package:video_compress/src/video_compress/video_compressor.dart:21:45)
I/flutter (20324): #5      VideoCompress (package:video_compress/src/video_compress/video_compressor.dart:30:56)
I/flutter (20324): #6      computeCompression (package:myapppackage/main/api.dart:24:10)
I/flutter (20324): #7      _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:84:34)
I/flutter (20324): #8      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:91:65)
I/flutter (20324): #9      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:90:5)
I/flutter (20324): #10     Timeline.timeSync (dart:developer/timelin
I/flutter (20324): ----------------------------------------------------
```

**Comment by Tom3652** [comment]
Unfortunately not :/
