### ISSUE TITLE
Unsupported value: 'kotlin.Unit' when using probably VideoCompress.deleteAllCache()

### ISSUE THREAD

**Issue by Tom3652** [jonataslaw/VideoCompress#144]
Hello again (from the last issue) !

I have this error when trying to delete all the cache files with ```VideoCompress.deleteAllCache()``` :

```
E/MethodChannel#video_compress(24654): Failed to handle method call
E/MethodChannel#video_compress(24654): java.lang.IllegalArgumentException: Unsupported value: 'kotlin.Unit' of type 'class kotlin.Unit'
E/MethodChannel#video_compress(24654): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:292)
E/MethodChannel#video_compress(24654): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:59)
E/MethodChannel#video_compress(24654): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/MethodChannel#video_compress(24654): 	at com.example.video_compress.VideoCompressPlugin.onMethodCall(VideoCompressPlugin.kt:68)
E/MethodChannel#video_compress(24654): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#video_compress(24654): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#video_compress(24654): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#video_compress(24654): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#video_compress(24654): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#video_compress(24654): 	at android.os.Looper.loop(Looper.java:184)
E/MethodChannel#video_compress(24654): 	at android.app.ActivityThread.main(ActivityThread.java:7864)
E/MethodChannel#video_compress(24654): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#video_compress(24654): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
E/MethodChannel#video_compress(24654): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:998)
```

Followed by :

```
E/DartMessenger(24654): Uncaught exception in binary message listener
E/DartMessenger(24654): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(24654): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
E/DartMessenger(24654): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:253)
E/DartMessenger(24654): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/DartMessenger(24654): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/DartMessenger(24654): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(24654): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/DartMessenger(24654): 	at android.os.Looper.loop(Looper.java:184)
E/DartMessenger(24654): 	at android.app.ActivityThread.main(ActivityThread.java:7864)
E/DartMessenger(24654): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(24654): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
E/DartMessenger(24654): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:998)
```

**Comment by Tom3652** [comment]
duplicate from #131

**Comment by ysiraparapu** [comment]
I am also facing same issue. How was this issue resolved?
