### ISSUE TITLE
Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by aravind-b-dev** [jonataslaw/VideoCompress#150]
i have used this code to get the progress

     _subscription =
        VideoCompress.compressProgress$.subscribe((progress) {
          debugPrint('progress: $progress');
          setState(() {
            progres = progress;
          });
        });

>>>  and my console

`
The relevant error-causing widget was: 
  ChangeNotifierProvider<ChatDelete> ChangeNotifierProvider:file:///C:/Users/ARAVIND/Desktop/upload/nritya-user-app/lib/screens/group_chat.dart:69:32
When the exception was thrown, this was the stack: 
#3      ObservableBuilder.subscribe (package:video_compress/src/progress_callback/subscription.dart:16:24)
#4      _GroupChatUIState.initState (package:nrithya/screens/group_chat.dart:119:41)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4805:57)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#10     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#20     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#27     _NestedHookElement.mount (package:nested/nested.dart:187:11)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#31     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#41     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#48     _NestedHookElement.mount (package:nested/nested.dart:187:11)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#52     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#62     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#69     _NestedHookElement.mount (package:nested/nested.dart:187:11)
#70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#73     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#75     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#83     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#90     _NestedHookElement.mount (package:nested/nested.dart:187:11)
#91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#94     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#104    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#111    _NestedHookElement.mount (package:nested/nested.dart:187:11)
#112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#115    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#117    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#118    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#125    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#132    _NestedHookElement.mount (package:nested/nested.dart:187:11)
#133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#136    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#138    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#146    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#153    _NestedHookElement.mount (package:nested/nested.dart:187:11)
#154    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#157    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#158    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#159    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#160    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#167    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#174    _NestedHookElement.mount (package:nested/nested.dart:187:11)
#175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#178    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#179    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#180    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#181    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#188    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#195    _NestedHookElement.mount (package:nested/nested.dart:187:11)
#196    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#197    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#199    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#200    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#201    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#202    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#209    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#216    _NestedHookElement.mount (package:nested/nested.dart:187:11)
#217    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#220    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#221    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#222    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#223    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#230    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#237    _NestedHookElement.mount (package:nested/nested.dart:187:11)
#238    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#239    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#241    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#242    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#243    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#244    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#251    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#258    _NestedHookElement.mount (package:nested/nested.dart:187:11)
#259    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#260    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#261    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#262    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#263    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#264    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#265    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#272    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#279    _NestedHookElement.mount (package:nested/nested.dart:187:11)
#280    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#281    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#282    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#283    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#284    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#285    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#286    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#293    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#300    _NestedHookElement.mount (package:nested/nested.dart:187:11)
#301    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#302    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#303    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#304    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#305    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#306    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#307    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#314    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#321    _NestedHookElement.mount (package:nested/nested.dart:187:11)
#322    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#323    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#324    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#325    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
#326    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#327    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#328    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (7 frames)
#335    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#342    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#349    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (47 frames)
#396    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#397    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#398    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1242:37)
#399    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1227:20)
#400    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2573:19)
#401    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1220:12)
#402    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#403    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1968:59)
#404    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:916:15)
#405    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1968:14)
#406    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#407    RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:422:5)
#408    RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:205:12)
#409    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#410    RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#411    _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#412    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#413    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#414    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#415    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#416    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#417    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#418    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#419    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#420    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#421    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#422    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#423    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#424    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#425    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#426    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#427    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#428    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#429    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#430    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#431    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#432    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#433    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#434    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#435    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#436    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#437    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097:7)
#438    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#439    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#440    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#441    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#442    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#443    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#444    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1388:11)
#445    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#446    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#447    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#448    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#449    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#450    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#451    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#452    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#453    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#454    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#455    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#456    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#457    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#458    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#459    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#460    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#461    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#462    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3420:14)
#463    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#464    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#465    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#466    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:745:15)
#467    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713:7)
#468    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
#469    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
#470    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#471    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#472    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#473    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#474    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#478    _invoke (dart:ui/hooks.dart:166:10)
#479    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#480    _drawFrame (dart:ui/hooks.dart:129:31)
(elided 6 frames from dart:async)`

**Comment by Amr-SymTerra** [comment]
When you run the code again the stream will already have the same listener attached to it, so use VideoCompress.dispose(); after finishing.

**Comment by shodafl** [comment]
HI! Tried you solution, but not receiving progress after new subscription. How I can fix this problem?

**Comment by tenhobi** [comment]
This issue is still there.

**Comment by tenhobi** [comment]
The solution is to rewrite `final compressProgress$ = ObservableBuilder<double>();` to `StreamController<double> _progressStream = StreamController.broadcast();`. It is breaking, it has different API `.subscribe` vs `.listen`, cc @jonataslaw

**Comment by Tarhex** [comment]
@tenhobi 

> The solution is to rewrite `final compressProgress$ = ObservableBuilder<double>();` to `StreamController<double> _progressStream = StreamController.broadcast();`. It is breaking, it has different API `.subscribe` vs `.listen`, cc [@jonataslaw](https://github.com/jonataslaw)

How did solve this?
