### ISSUE TITLE
Unable to compress video (h264): java.lang.IllegalStateException: No retriever available

### ISSUE THREAD

**Issue by crtl** [jonataslaw/VideoCompress#169]
Ive recently upgraded to flutter 2.10.3 and had to use video_compress from `master` branch because of kotlin version issue.

Now it fails to compress specific videos (i guess its h264).
If I want to compress video from camera it works, if I take video from gallery some work and some dont.
Videos that dont work can be downloaded here: https://test-videos.co.uk/bigbuckbunny/mp4-h264

When trying to compress the video the following java exception is printed and `VideoCompress.compressVideo` returns `null`.
```
[de.app.CompressVideoBloc] startCompression /data/user/0/de.app.app.dev/cache/image_picker141464111061834127.mp4 30fps
I/OpenGLRenderer(28944): Davey! duration=156806ms; Flags=1, FrameTimelineVsyncId=4729593, IntendedVsync=75269371625331, Vsync=75269371625331, InputEventId=474747977, HandleInputStart=75269371932972, AnimationStart=75269371934170, PerformTraversalsStart=75269371935108, DrawStart=75269386176932, FrameDeadline=75269421458663, FrameInterval=75269371929431, FrameStartTime=16666666, SyncQueued=75269386496620, SyncStart=75269386533651, IssueDrawCommandsStart=75269386590839, SwapBuffers=75269389220995, FrameCompleted=75426177845364, DequeueBufferDuration=1876354, QueueBufferDuration=540417, GpuCompleted=75426177845364, SwapBuffersCompleted=75269390070839, DisplayPresentTime=0, 
D/MPEG4Writer(28944): PreAllocation disabled. fallocate : Operation not supported on transport endpoint, 95
I/TranscodeEngine(28944): transcode(): called...
I/DefaultDataSource(80743225)(28944): getTrackFormat(VIDEO)
I/DefaultDataSource(80743225)(28944): getTrackFormat(AUDIO)
I/DefaultDataSource(80743225)(28944): deinitialize(): releasing...
I/DefaultDataSource(80743225)(28944): getTrackFormat(VIDEO)
I/Tracks  (28944): init: videoStatus=ABSENT, resolvedVideoStatus=ABSENT, videoFormat={}
I/Tracks  (28944): init: audioStatus=ABSENT, resolvedAudioStatus=ABSENT, audioFormat={}
I/TranscodeEngine(28944): Created Tracks, Segments, Timer...
I/DefaultDataSource(80743225)(28944): getLocation()
E/TranscodeEngine(28944): Unexpected error while transcoding.
E/TranscodeEngine(28944): java.lang.IllegalStateException: No retriever available
E/TranscodeEngine(28944): 	at android.media.MediaMetadataRetriever.nativeExtractMetadata(Native Method)
E/TranscodeEngine(28944): 	at android.media.MediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.java:427)
E/TranscodeEngine(28944): 	at com.otaliastudios.transcoder.source.DefaultDataSource.getLocation(DefaultDataSource.java:226)
E/TranscodeEngine(28944): 	at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$location$1.invoke(DefaultTranscodeEngine.kt:50)
E/TranscodeEngine(28944): 	at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$location$1.invoke(DefaultTranscodeEngine.kt:25)
E/TranscodeEngine(28944): 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
E/TranscodeEngine(28944): 	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
E/TranscodeEngine(28944): 	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
E/TranscodeEngine(28944): 	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167)
E/TranscodeEngine(28944): 	at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.<init>(DefaultTranscodeEngine.kt:50)
E/TranscodeEngine(28944): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:32)
E/TranscodeEngine(28944): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
E/TranscodeEngine(28944): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
E/TranscodeEngine(28944): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
E/TranscodeEngine(28944): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/TranscodeEngine(28944): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/TranscodeEngine(28944): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/TranscodeEngine(28944): 	at java.lang.Thread.run(Thread.java:920)
I/flutter (28944): hideLoader
[de.app.CompressVideoBloc] compressionComplete null
D/BufferPoolAccessor2.0(28944): evictor expired: 1, evicted: 0

```

Dart code for compression is:
```dart
final info = await VideoCompress.compressVideo(
        file.path,
        frameRate: config.fps ?? 30,
        quality: config.quality ?? VideoQuality.DefaultQuality,
        deleteOrigin: false,
);
```

Flutter doctor:
```
[✓] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19041.1415], locale de-DE)
    • Flutter version 2.10.3 at C:\Users\User\fvm\versions\2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\dev\android\sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = D:\dev\android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.
```

**Comment by Adherentman** [comment]
Error still exist
log: 
````
V/Segment(VIDEO,0)(14480): canAdvance(): state=State.Wait
V/TranscodeEngine(14480): transcode(): executed step=0 advanced=false completed=false
V/Segment(AUDIO,0)(14480): canAdvance(): state=State.Wait
V/Segment(VIDEO,0)(14480): canAdvance(): state=State.Wait
V/Pipeline(Audio)(14480): execute(): starting. head=0 steps=6 remaining=6
V/DefaultDataSource(1)(14480): readTrack(): time=69659, render=true, end=-1
I/Decoder(AUDIO,1)(14480): drain(): got INFO_OUTPUT_FORMAT_CHANGED, handling format and retrying. format={encoder-delay=2048, sample-rate=44100, mime=audio/raw, channel-count=2, encoder-padding=0}
I/AudioEngine(1)(14480): handleRawFormat({encoder-delay=2048, sample-rate=44100, mime=audio/raw, channel-count=2, encoder-padding=0})
V/Decoder(AUDIO,1)(14480): drain(): returning State.Ok(com.otaliastudios.transcoder.internal.codec.DecoderData@be51279)
E/TranscodeEngine(14480): Unexpected error while transcoding.
E/TranscodeEngine(14480): java.lang.IllegalArgumentException: Failed requirement.
E/TranscodeEngine(14480): 	at com.otaliastudios.transcoder.internal.audio.ChunkQueue.enqueue(chunks.kt:28)
E/TranscodeEngine(14480): 	at com.otaliastudios.transcoder.internal.audio.AudioEngine.enqueue(AudioEngine.kt:59)
E/TranscodeEngine(14480): 	at com.otaliastudios.transcoder.internal.audio.AudioEngine.enqueue(AudioEngine.kt:21)
E/TranscodeEngine(14480): 	at com.otaliastudios.transcoder.internal.pipeline.QueuedStep.step(steps.kt:40)
E/TranscodeEngine(14480): 	at com.otaliastudios.transcoder.internal.pipeline.Pipeline.executeStep(Pipeline.kt:51)
E/TranscodeEngine(14480): 	at com.otaliastudios.transcoder.internal.pipeline.Pipeline.execute(Pipeline.kt:28)
E/TranscodeEngine(14480): 	at com.otaliastudios.transcoder.internal.Segment.advance(Segment.kt:18)
E/TranscodeEngine(14480): 	at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:114)
E/TranscodeEngine(14480): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
E/TranscodeEngine(14480): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
E/TranscodeEngine(14480): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
E/TranscodeEngine(14480): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
E/TranscodeEngine(14480): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/TranscodeEngine(14480): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/TranscodeEngine(14480): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/TranscodeEngine(14480): 	at java.lang.Thread.run(Thread.java:929)
I/Decoder(VIDEO,1)(14480): release(): releasing codec. dequeuedInputs=0 dequeuedOutputs=0
W/ACodec  (14480): forcing OMX state to Idle when received shutdown in ExecutingState
I/flutter (14480): compressedVideoInfo null
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
```
