### ISSUE TITLE
Cannot compress H264 AAC after upgrading from 3.1.0 to 3.1.1

### ISSUE THREAD

**Issue by binlebin** [jonataslaw/VideoCompress#179]
My compression fails after I upgrade from 3.1.0 to 3.1.1 when transcoding a H264 AAC video on Android

E/TranscodeEngine( 4637): Unexpected error while transcoding.
E/TranscodeEngine( 4637): java.lang.IllegalArgumentException: Failed requirement.
E/TranscodeEngine( 4637): 	at com.otaliastudios.transcoder.internal.audio.ChunkQueue.enqueue(chunks.kt:28)
E/TranscodeEngine( 4637): 	at com.otaliastudios.transcoder.internal.audio.AudioEngine.enqueue(AudioEngine.kt:59)
E/TranscodeEngine( 4637): 	at com.otaliastudios.transcoder.internal.audio.AudioEngine.enqueue(AudioEngine.kt:21)
E/TranscodeEngine( 4637): 	at com.otaliastudios.transcoder.internal.pipeline.QueuedStep.step(steps.kt:40)
E/TranscodeEngine( 4637): 	at com.otaliastudios.transcoder.internal.pipeline.Pipeline.executeStep(Pipeline.kt:51)
E/TranscodeEngine( 4637): 	at com.otaliastudios.transcoder.internal.pipeline.Pipeline.execute(Pipeline.kt:28)
E/TranscodeEngine( 4637): 	at com.otaliastudios.transcoder.internal.Segment.advance(Segment.kt:18)
E/TranscodeEngine( 4637): 	at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:114)
E/TranscodeEngine( 4637): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
E/TranscodeEngine( 4637): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
E/TranscodeEngine( 4637): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
E/TranscodeEngine( 4637): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)

I believe this error comes from the new Android transcoding library 0.10.4

https://github.com/natario1/Transcoder/issues/153

I applied the fix 

https://github.com/natario1/Transcoder/pull/158

The fix would work on the Transcoder demo app but wouldn't work when I use video_compress

**Comment by beriaanirudh** [comment]
@binlebin I am facing the same issue https://github.com/natario1/Transcoder/pull/158 while using video_compress. This has started happening since 3.1.1 , and not in 3.1.0, and due to the nature of my other dependencies, I cannot downgrade to 3.1.1 . I tried using master branch, but it was no go. Did you find any solution to this?

**Comment by jonataslaw** [comment]
I think I will internalize this library.
The fixes were never merged, and this is freezing Flutter library development.
