### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by HenrikVL** [jonataslaw/VideoCompress#184]
# Unhandled Exception: Null check operator used on a null value

I am encountering an error when trying to compress videos. I am testing the app on an Iphone 12 pro.

I have tried using the following versions of the package:
- 3.1.1
- 3.1.0
- 3.0.0

My system:
- Computer: Macbook pro m1 13 (Monterey 12.4)
- Phone for testing: Iphone 12 pro (15.5)
- IDE: Visual Studio Code
- Flutter version: 3.0.3

My code:
```dart
print("before compression");

final info = await VideoCompress.compressVideo(
  widget.filePath,
  quality: VideoQuality.MediumQuality,
  deleteOrigin: false,
  includeAudio: false,
);

print("after compression");

setState(() {
  compressedInfo = info!.path!; // Dart complains if I don't run a null-check here
  print("info set");
});
```

Error:
```
The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888
flutter: before compression
flutter: VideoCompress: You can try to subscribe to the
flutter:       compressProgress$ stream to know the compressing state.
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
#0      new MediaInfo.fromJson (package:video_compress/src/media/media_info.dart:43:21)
#1      Compress.compressVideo (package:video_compress/src/video_compress/video_compressor.dart:154:24)
<asynchronous suspension>
#2      _VideoPageState.build.<anonymous closure> (package:apiir_bikefit/pages/record/video_page.dart:65:28)
<asynchronous suspension>
```

I first assumed that there was something wrong with the way I was handling the result of the compression (`info`) or that I had implemented the async await wrong. However, after trying different methods and researching online I can't seem to find the problem. 

Additionally, it seems that `print("after compression");` is never reached, indicating that there is something wrong with the compression function (though I'm not 100% sure).

Could this be a bug in the package?

**Comment by expertdev-designer** [comment]
@HenrikVL @jonataslaw i also have same issue

**Comment by SomeoneAndNoone** [comment]
I also have the same issue

**Comment by caleb654** [comment]
Also having this issue. Can confirm what @SomeoneAndNoone said as well.

**Comment by eegets** [comment]
video_compress Verison:
* video_compress: ^3.1.1

My System:
* MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

Flutter code:
```flutter
...
  if (Platform.isMacOS) {

      print("MacOs");

      final info = await VideoCompress.getMediaInfo("/Users/wangkai/Downloads/shijiannihao.mkv");
      final thumbnail = await VideoCompress.getFileThumbnail("/Users/wangkai/Downloads/shijiannihao.mkv");  //getFileThumbnail no working
      print("Print: info:$info");
      print("thumbnail: $thumbnail");
    }
...
```

Log Print:
```flutter
flutter: MacOs
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      new MediaInfo.fromJson (package:video_compress/src/media/media_info.dart:43:21)
#1      Compress.getMediaInfo (package:video_compress/src/video_compress/video_compressor.dart:104:22)
<asynchronous suspension>
#2      _MyAppState.getVideoInfo (package:happy_sing/main.dart:51:20)
<asynchronous suspension>

```
### I have two questions
* 1: There is no callback after the `VideoCompress.getFileThumbnail()` method is executed
* 2: `VideoCompress.getMediaInfo()` returned Null check operator used on a null value error

However, the above two methods can return normally and get the value when executed on an Android phone

**Comment by sharadgoregore** [comment]
> Also having this issue. Can confirm what @SomeoneAndNoone said as well.

Thanks bro

**Comment by sharadgoregore** [comment]
> I also have the same issue. I found out that it is happening when I set `include_audio` to `false`.

Thanks man..it worked for me

**Comment by JoergPf** [comment]
Same here, is there a solution besides setting include_audio to false?

**Comment by marinaaraujo97** [comment]
Probable related to #203

**Comment by meridorkobi** [comment]
I have the same exception 
using ^3.1.2


`  static Future<MediaInfo?> compressVideo(File file) async {
    MediaInfo? mediainfo;
    try {
      await VideoCompress.setLogLevel(0);
      mediainfo = await VideoCompress.compressVideo(file.path,
          quality: VideoQuality.MediumQuality,
          includeAudio: false,
          deleteOrigin: false
      );
      return mediainfo;
    } catch (e) {
      VideoCompress.cancelCompression(); //If any error occurs during compression, the process is stopped.
    }
    return null;
  }
`

**Comment by singhmukesh2023** [comment]
> > I also have the same issue. I found out that it is happening when I set `include_audio` to `false`.
> 
> Thanks man..it worked for me

Not Worked with includeAudio true and false. Version - 3.1.3, device POCCO F1, Android Version - 10

**Comment by LiamMarega** [comment]
+1
