### ISSUE TITLE
Failed to stop the muxer

### ISSUE THREAD

**Issue by Amitzala143** [jonataslaw/VideoCompress#191]
I am facing this issue while compressing video recorded by. camera

W/DefaultDataSink(13524): Failed to release the muxer.
W/DefaultDataSink(13524): java.lang.IllegalStateException: Failed to stop the muxer
W/DefaultDataSink(13524): 	at android.media.MediaMuxer.nativeStop(Native Method)
W/DefaultDataSink(13524): 	at android.media.MediaMuxer.stop(MediaMuxer.java:486)
W/DefaultDataSink(13524): 	at android.media.MediaMuxer.release(MediaMuxer.java:726)
W/DefaultDataSink(13524): 	at com.otaliastudios.transcoder.sink.DefaultDataSink.release(DefaultDataSink.java:224)
W/DefaultDataSink(13524): 	at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.cleanup(DefaultTranscodeEngine.kt:137)
W/DefaultDataSink(13524): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:63)
W/DefaultDataSink(13524): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
W/DefaultDataSink(13524): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
W/DefaultDataSink(13524): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
W/DefaultDataSink(13524): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/DefaultDataSink(13524): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/DefaultDataSink(13524): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by RajSolai** [comment]
Stuck with same Issue

**Comment by isyedaliraza** [comment]
Hi, there I am having the same issue. It was working fine last night but now it is giving this error.

**Comment by isyedaliraza** [comment]
Is there any update on this? Did anyone fix this issue?

**Comment by Amitzala143** [comment]
> Is there any update on this? Did anyone fix this issue?

no i didn't. find yet

**Comment by mbfakourii** [comment]
@jonataslaw You may check this issue, it is very important

**Comment by wsb1689** [comment]
hi bro,have you sovled it?

**Comment by isyedaliraza** [comment]
For me, the issue was not solved and I solved it by shifting to [ffmpeg_kit_flutter](https://pub.dev/packages/ffmpeg_kit_flutter) package.

**Comment by nixrajput** [comment]
Getting the same error, but it's working fine with `includeAudio` option `true`.

```dart
var info = await VideoCompress.compressVideo(
    videoFile.path,
    deleteOrigin: false,
    includeAudio: false,
    quality: VideoQuality.DefaultQuality,
);
```
Has anyone solved this issue??
