### ISSUE TITLE
Error occurred during video compression

### ISSUE THREAD

**Issue by nixrajput** [jonataslaw/VideoCompress#196]
This error is occurring during video compression and `includeAudio` option is `true`.
```
E/TranscodeEngine( 8526): Unexpected error while transcoding.
[        ] E/TranscodeEngine( 8526): java.lang.IllegalStateException: Error during stop(), muxer would have stopped already
[        ] E/TranscodeEngine( 8526): 	at android.media.MediaMuxer.nativeStop(Native Method)
[        ] E/TranscodeEngine( 8526): 	at android.media.MediaMuxer.stop(MediaMuxer.java:484)
[        ] E/TranscodeEngine( 8526): 	at com.otaliastudios.transcoder.sink.DefaultDataSink.stop(DefaultDataSink.java:218)
[        ] E/TranscodeEngine( 8526): 	at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:132)
[        ] E/TranscodeEngine( 8526): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
[        ] E/TranscodeEngine( 8526): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
[        ] E/TranscodeEngine( 8526): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
[        ] E/TranscodeEngine( 8526): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
[        ] E/TranscodeEngine( 8526): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[        ] E/TranscodeEngine( 8526): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] E/TranscodeEngine( 8526): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] E/TranscodeEngine( 8526): 	at java.lang.Thread.run(Thread.java:920)
[        ] I/Decoder(VIDEO,22)( 8526): release(): releasing codec. dequeuedInputs=0 dequeuedOutputs=0
[        ] D/MPEG4Writer( 8526): reset()
[        ] D/MPEG4Writer( 8526): Video track stopping. Stop source
[        ] E/MPEG4Writer( 8526): Stop() called but track is not started or stopped
[        ] D/MPEG4Writer( 8526): Audio track stopping. Stop source
[        ] E/MPEG4Writer( 8526): Stop() called but track is not started or stopped
[        ] I/DataSources( 8526): release(): releasing...
[        ] I/DataSources( 8526): deinitializing com.otaliastudios.transcoder.source.UriDataSource@928dd55... (isInit=true)
[        ] I/DefaultDataSource(22)( 8526): deinitialize(): deinitializing...
[        ] I/DataSources( 8526): deinitializing com.otaliastudios.transcoder.source.UriDataSource@928dd55... (isInit=false)
[        ] I/DataSources( 8526): release(): released.
```
With option `includeAudio` to `false`, compression is working fine.
Please solve this issue.

**Comment by RobotKSR** [comment]
Hello! Same issue for me. I have to mention this issue happens in v. 3.1.1 of plugin and never in 3.1.0 for me.

**Comment by PaulBout1** [comment]
see PR: https://github.com/jonataslaw/VideoCompress/pull/189

**Comment by y-vnk** [comment]
still facing this issue
