### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported value: 'kotlin.Unit' of type 'class kotlin.Unit'

### ISSUE THREAD

**Issue by cnkygmr** [jonataslaw/VideoCompress#221]
`MediaInfo? mediaInfo = await VideoCompress.compressVideo(file.path, quality: VideoQuality.MediumQuality, includeAudio: true);`

I use it this way, it works normally, but when I leave the page I am processing, it gives the following error?
I want it to continue doing it in the background but it throws an error

```
E/MethodChannel#video_compress( 3765): Failed to handle method call
E/MethodChannel#video_compress( 3765): java.lang.IllegalArgumentException: Unsupported value: 'kotlin.Unit' of type 'class kotlin.Unit'
E/MethodChannel#video_compress( 3765): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/MethodChannel#video_compress( 3765): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:61)
E/MethodChannel#video_compress( 3765): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
E/MethodChannel#video_compress( 3765): 	at com.example.video_compress.VideoCompressPlugin.onMethodCall(VideoCompressPlugin.kt:67)
E/MethodChannel#video_compress( 3765): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#video_compress( 3765): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#video_compress( 3765): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#video_compress( 3765): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#video_compress( 3765): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#video_compress( 3765): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#video_compress( 3765): 	at android.os.Looper.loop(Looper.java:193)
E/MethodChannel#video_compress( 3765): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#video_compress( 3765): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#video_compress( 3765): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#video_compress( 3765): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/DartMessenger( 3765): Uncaught exception in binary message listener
E/DartMessenger( 3765): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger( 3765): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/DartMessenger( 3765): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:278)
E/DartMessenger( 3765): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger( 3765): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger( 3765): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger( 3765): 	at android.os.Handler.handleCallback(Handler.java:873)
E/DartMessenger( 3765): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger( 3765): 	at android.os.Looper.loop(Looper.java:193)
E/DartMessenger( 3765): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/DartMessenger( 3765): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger( 3765): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/DartMessenger( 3765): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by karamatpkid** [comment]
Same error is here, any update?

**Comment by karamatpkid** [comment]
E/MethodChannel#video_compress( 9851): Failed to handle method call
E/MethodChannel#video_compress( 9851): java.lang.IllegalArgumentException: Unsupported value: 'kotlin.Unit' of type 'class kotlin.Unit'
E/MethodChannel#video_compress( 9851): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/MethodChannel#video_compress( 9851): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:61)
E/MethodChannel#video_compress( 9851): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
E/MethodChannel#video_compress( 9851): 	at com.example.video_compress.VideoCompressPlugin.onMethodCall(VideoCompressPlugin.kt:67)
E/MethodChannel#video_compress( 9851): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#video_compress( 9851): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#video_compress( 9851): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#video_compress( 9851): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#video_compress( 9851): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#video_compress( 9851): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#video_compress( 9851): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#video_compress( 9851): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#video_compress( 9851): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/MethodChannel#video_compress( 9851): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#video_compress( 9851): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#video_compress( 9851): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/DartMessenger( 9851): Uncaught exception in binary message listener
E/DartMessenger( 9851): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger( 9851): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/DartMessenger( 9851): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:278)
E/DartMessenger( 9851): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger( 9851): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger( 9851): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger( 9851): 	at android.os.Handler.handleCallback(Handler.java:942)
E/DartMessenger( 9851): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger( 9851): 	at android.os.Looper.loopOnce(Looper.java:226)
E/DartMessenger( 9851): 	at android.os.Looper.loop(Looper.java:313)
E/DartMessenger( 9851): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/DartMessenger( 9851): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger( 9851): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/DartMessenger( 9851): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by lakshmansha** [comment]
I am also facing the same issue.

**Comment by gOzaru** [comment]
I think the problem is in video format.
It should be mp4 only.
And it cannot be using Adobe Media Encoder to compile it.
Sometime the format is read as mp4v and that is not compatible and caused such error.

**Comment by karamatpkid** [comment]
Not due to Mp4, because in my folder all videos are in MP4.

**Comment by kunatastic** [comment]
Fixed by #293. I’ve proposed a solution, but the PR hasn’t been merged yet.
