### ISSUE TITLE
Fatal error while transcoding, this might be invalid format or bug in engine or Android.

### ISSUE THREAD

**Issue by Amshaf123** [jonataslaw/VideoCompress#256]
E/Transcoder(12214): Fatal error while transcoding, this might be invalid format or bug in engine or Android.
E/Transcoder(12214): java.lang.IllegalArgumentException: could not access /storage/emulated/0/Android/data/com.rickkr.app/files/2024-02-19T10:53:26.504182.mp4
E/Transcoder(12214): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:388)
E/Transcoder(12214): 	at com.otaliastudios.transcoder.source.UriDataSource.applyRetriever(UriDataSource.java:33)
E/Transcoder(12214): 	at com.otaliastudios.transcoder.source.DefaultDataSource.ensureMetadata(DefaultDataSource.java:41)
E/Transcoder(12214): 	at com.otaliastudios.transcoder.source.DefaultDataSource.getLocation(DefaultDataSource.java:138)
E/Transcoder(12214): 	at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:316)
E/Transcoder(12214): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:150)
E/Transcoder(12214): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:140)
E/Transcoder(12214): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/Transcoder(12214): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/Transcoder(12214): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/Transcoder(12214): 	at java.lang.Thread.run(Thread.java:1012)

**Comment by kapil708** [comment]
Any update?
