### ISSUE TITLE
MissingPluginException(No implementation found for method setLogLevel on channel video_compress)

### ISSUE THREAD

**Issue by Tetrazine** [jonataslaw/VideoCompress#258]
I'm using video_compress 3.1.0, flutter 3.19.1 and Dart 3.3.0

Debugging console output:
flutter: Video compression canceled with error: MissingPluginException(No implementation found for method setLogLevel on channel video_compress)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method cancelCompression on channel video_compress)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      Compress._invoke (package:video_compress/src/video_compress/video_compressor.dart:41:13)
<asynchronous suspension>
#2      Compress.cancelCompression (package:video_compress/src/video_compress/video_compressor.dart:168:5)
<asynchronous suspension>

And this is the corresponding code:

CustomTextButton(
                            onPressed: () async {                         
                              MediaInfo? info = await controller.compressVideo(
                                  Get.find<GameController>().videoFile3);
                            },
                            text: 'Compress Video',
                          ),
                          
     Future<MediaInfo?> compressVideo(File? file) async {
    try {
      await VideoCompress.setLogLevel(0);
      return VideoCompress.compressVideo(
        file!.path,
        quality: VideoQuality.MediumQuality,
        includeAudio: true,
        deleteOrigin: false,
      );
    } catch (e) {
      VideoCompress.cancelCompression();
      debugPrint('Video compression canceled with error: $e');
    }
  }

**Comment by kkuivi** [comment]
@Tetrazine Were you able to find a solution? I seem to be running into the same issue. 

Flutter clean + Flutter pub get does not fix the issue for me

**Comment by Tetrazine** [comment]
yes i solved the problem by using the "video_compress_v2" package instead of the "video_compress" package. hope this also works for you!

**Comment by kkuivi** [comment]
Did you do anything besides importing the package in the pubspec.yaml? I tried video_compressV2 and I am still running into the MissingPluginException error.

**Comment by Tetrazine** [comment]
No sorry, i didn't do anything else besides importing it in the pubsepec.yaml. And yes it's working for Android and iOS.
