### ISSUE TITLE
E/TranscodeEngine(16841): Unexpected error while transcoding.

### ISSUE THREAD

**Issue by y-vnk** [jonataslaw/VideoCompress#279]
When I try to upload Video file which as audio, it is throwing below error. 

`E/TranscodeEngine(16841): Unexpected error while transcoding.
E/TranscodeEngine(16841): java.lang.IllegalStateException: Input channel count not supported: 6
E/TranscodeEngine(16841): 	at com.otaliastudios.transcoder.internal.audio.remix.AudioRemixer$Companion.get$lib_release(AudioRemixer.kt:26)
E/TranscodeEngine(16841): 	at com.otaliastudios.transcoder.internal.audio.AudioEngine.handleRawFormat(AudioEngine.kt:47)
E/TranscodeEngine(16841): 	at com.otaliastudios.transcoder.internal.codec.Decoder.drain(Decoder.kt:99)
E/TranscodeEngine(16841): 	at com.otaliastudios.transcoder.internal.pipeline.QueuedStep.step(steps.kt:42)
E/TranscodeEngine(16841): 	at com.otaliastudios.transcoder.internal.pipeline.Pipeline.executeStep(Pipeline.kt:51)
E/TranscodeEngine(16841): 	at com.otaliastudios.transcoder.internal.pipeline.Pipeline.execute(Pipeline.kt:28)
E/TranscodeEngine(16841): 	at com.otaliastudios.transcoder.internal.Segment.advance(Segment.kt:18)
E/TranscodeEngine(16841): 	at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:114)
E/TranscodeEngine(16841): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
E/TranscodeEngine(16841): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
E/TranscodeEngine(16841): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
E/TranscodeEngine(16841): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
E/TranscodeEngine(16841): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/TranscodeEngine(16841): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/TranscodeEngine(16841): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/TranscodeEngine(16841): 	at java.lang.Thread.run(Thread.java:920)`

I have tried with example from the lib, it is also throwing same error.

**Comment by y-vnk** [comment]
@jonataslaw Can you please check this once?

**Comment by khanhduy122** [comment]
I also have this error with some videos. Do you have a solution for it?

**Comment by delizondo** [comment]
The the same error running my app in Android 10. 
Tested in Android 14, and everything worked fine

**Comment by nafiskabbo** [comment]
Same error getting! Any solution?

**Comment by nafiskabbo** [comment]
Added fix and pushed changes. Can anyone check and approve it?
https://github.com/jonataslaw/VideoCompress/pull/287

**Comment by christianr11** [comment]
Got the same error when i upgraded my gradle version.
