### ISSUE TITLE
Plugin has conflicts with firebase firebase_messaging how to solve this?

### ISSUE THREAD

**Issue by VikashIOS** [jonataslaw/VideoCompress#33]
E/MethodChannel#plugins.flutter.io/firebase_messaging(29702): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_messaging(29702): java.lang.IllegalStateException: registrar.activity() must not be null
E/MethodChannel#plugins.flutter.io/firebase_messaging(29702):   at com.example.video_compress.VideoCompressPlugin$Companion.registerWith(VideoCompressPlugin.kt:132)
E/MethodChannel#plugins.flutter.io/firebase_messaging(29702):   at com.example.video_compress.VideoCompressPlugin.registerWith(VideoCompressPlugin.kt)
E/MethodChannel#plugins.flutter.io/firebase_messaging(29702):   at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:65)
E/MethodChannel#plugins.flutter.io/firebase_messaging(29702):   at com.devbits.camiotalk.Application.registerWith(Application.kt:17)
E/MethodChannel#plugins.flutter.io/firebase_messaging(29702):   at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.startBackgroundIsolate(FlutterFirebaseMessagingService.java:164)
E/MethodChannel#plugins.flutter.io/firebase_messaging(29702):   at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.onMethodCall(FirebaseMessagingPlugin.java:176)

I/flutter (29702): [2020-08-09 15:28:36.205762 | ConsoleHandler | INFO] PlatformException(error, registrar.activity() must not be null, null)
I/flutter (29702): [2020-08-09 15:28:36.205901 | ConsoleHandler | INFO] 
I/flutter (29702): [2020-08-09 15:28:36.207027 | ConsoleHandler | INFO] ------- STACK TRACE -------
I/flutter (29702): [2020-08-09 15:28:36.265416 | ConsoleHandler | INFO] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
I/flutter (29702): [2020-08-09 15:28:36.265869 | ConsoleHandler | INFO] #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
I/flutter (29702): [2020-08-09 15:28:36.266165 | ConsoleHandler | INFO] <asynchronous suspension>
I/flutter (29702): [2020-08-09 15:28:36.266441 | ConsoleHandler | INFO] #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12

**Comment by jonataslaw** [comment]
Does this still occur in the latest version?
