### ISSUE TITLE
Compression crash (v2.1.1)

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [jonataslaw/VideoCompress#82]
Hi, 
On IOS, picking a video from library; then trying to compress it crash app 

```dart
final MediaInfo mediaInfo = await VideoCompress.compressVideo(
widget.path, 
quality: VideoQuality.MediumQuality, 
deleteOrigin: false, 
includeAudio: true);
```

```dart
Error : Invalid argument(s) (path): Must not be null 
```
i double check, path is never null and exists.
adding some logging show that 

```dart
At some point, data is reased, and it remain only ::
{"isCancel":false}
```
v2.1.1 should correct this according some issue, but its not my case.
Thanks, Nelson

**Comment by hyobbb** [comment]
I am having the same problem.

```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s) (path): Must not be null
#0      ArgumentError.checkNotNull (dart:core/errors.dart:194)
#1      _Directory._checkNotNull (dart:io/directory_impl.dart:276)
#2      new _File (dart:io/file_impl.dart:205)
#3      new File (dart:io/file.dart:250)
#4      new MediaInfo.fromJson (package:video_compress/src/media/media_info.dart:24)
#5      Compress.compressVideo (package:video_compress/src/video_compress/video_compressor.dart:158)
```

I also checked that filePath and ExistSync. It has no problem in Android.

**Comment by mrgnhnt96** [comment]
I am getting the same error. Its occuring in `video_compressor.dart` line 158. It is trying to convert json into the MediaInfo class. It is receiving only a string of "{"isCancel":false}". 

With a little debugging I noticed that if I call `await VideoCompress.cancelCompression();`  it will not through the error and compress the video. However, when I call `await VideoCompress.getFileThumbnail...)` it just stops running without an errors.

**Comment by arashbi** [comment]
I have the same problem. The method   `Future<T> _invoke<T>(String name, [Map<String, dynamic> params]) async ` doesn't work properly it seems. It returns immediately with no good result
