### ISSUE TITLE
Getting this error on compressing video obtained after trimming using the flutter package video_trimmer.

### ISSUE THREAD

**Issue by harjotsingh1999** [jonataslaw/VideoCompress#83]
E/Transcoder( 9380): Fatal error while transcoding, this might be invalid format or bug in engine or Android.
E/Transcoder( 9380): java.lang.IllegalArgumentException
E/Transcoder( 9380): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:214)
E/Transcoder( 9380): 	at com.otaliastudios.transcoder.source.UriDataSource.applyRetriever(UriDataSource.java:33)
E/Transcoder( 9380): 	at com.otaliastudios.transcoder.source.DefaultDataSource.ensureMetadata(DefaultDataSource.java:41)
E/Transcoder( 9380): 	at com.otaliastudios.transcoder.source.DefaultDataSource.getLocation(DefaultDataSource.java:138)
E/Transcoder( 9380): 	at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:316)
E/Transcoder( 9380): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
E/Transcoder( 9380): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
E/Transcoder( 9380): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/Transcoder( 9380): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Transcoder( 9380): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Transcoder( 9380): 	at java.lang.Thread.run(Thread.java:919)

The thumbnail generation method works fine on the same file.

**Comment by BilalPervez** [comment]
I'm facing same issue Any update?

**Comment by harjotsingh1999** [comment]
@BilalPervez not yet.

**Comment by RenanDelfanti** [comment]
Same issue here

**Comment by Abacaxi-Nelson** [comment]
same here.

**Comment by BilalPervez** [comment]
Guy you need to compress the video first then trim it, 
this is only solution that get right now to get rid of this problem.

**Comment by ajosecueto** [comment]
same issue

**Comment by BilalPervez** [comment]
@ajosecueto did you try to compress it first and then apply trimming on it and still facing the same issue?

**Comment by ajosecueto** [comment]
@BilalPervez Really i'm able to compress without problem using a real device, that happens only in android emulator... i think is because the path where video trimming is not full accessible... idk

**Comment by ZaidrazaNarsinh** [comment]
> Guy you need to compress the video first then trim it, this is only solution that get right now to get rid of this problem.
I was finding the solution since last 2 days but this worked for me..
Thank man!

**Comment by rishabhOpenxcell** [comment]
tempDir = await getTemporaryDirectory();

file = await File(tempDir.path+'Vid${DateTime.now().millisecondsSinceEpoch}.mp4').writeAsBytes(File(updatedPath).readAsBytesSync());

mediaInfo = await VideoCompress.compressVideo(
file.path,
quality: VideoQuality.Res960x540Quality,
deleteOrigin: false,
);

just make a temporary file in cache directory and then give its path in compress.
it will work!!
